--h2 versions
create table js_site_member
(
 Auto_serial_number bigint generated by default as identity,
 ID varchar(255),
 PW varchar(255),
 NickName varchar(255),
 primary key (Auto_serial_number)
);

--두 db를 연결하려면 ID에 unique 처리를 해야함!
ALTER TABLE js_site_member
ADD CONSTRAINT unique_id_constraint UNIQUE (ID);

CREATE TABLE Background_img (
    Auto_serial_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID VARCHAR(255) REFERENCES js_site_member(ID),
    file_name VARCHAR(255),
    file_path VARCHAR(255),
    file_size BIGINT,
    creation_time TIMESTAMP
);